// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using conference_rooms.Data;

#nullable disable

namespace conference_rooms.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("conference_rooms.Domain.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationHours")
                        .HasColumnType("integer");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("conference_rooms.Domain.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 50,
                            Cost = 2000m,
                            Name = "Зал А"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 100,
                            Cost = 3500m,
                            Name = "Зал В"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 30,
                            Cost = 1500m,
                            Name = "Зал С"
                        });
                });

            modelBuilder.Entity("conference_rooms.Domain.RoomService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RoomId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 500m,
                            Name = "Проєктор",
                            RoomId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cost = 300m,
                            Name = "Wi-Fi",
                            RoomId = 1
                        },
                        new
                        {
                            Id = 3,
                            Cost = 700m,
                            Name = "Звук",
                            RoomId = 1
                        },
                        new
                        {
                            Id = 4,
                            Cost = 500m,
                            Name = "Проєктор",
                            RoomId = 2
                        },
                        new
                        {
                            Id = 5,
                            Cost = 300m,
                            Name = "Wi-Fi",
                            RoomId = 2
                        },
                        new
                        {
                            Id = 6,
                            Cost = 700m,
                            Name = "Звук",
                            RoomId = 2
                        },
                        new
                        {
                            Id = 7,
                            Cost = 500m,
                            Name = "Проєктор",
                            RoomId = 3
                        },
                        new
                        {
                            Id = 8,
                            Cost = 300m,
                            Name = "Wi-Fi",
                            RoomId = 3
                        },
                        new
                        {
                            Id = 9,
                            Cost = 700m,
                            Name = "Звук",
                            RoomId = 3
                        });
                });

            modelBuilder.Entity("conference_rooms.Domain.Booking", b =>
                {
                    b.HasOne("conference_rooms.Domain.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("conference_rooms.Domain.RoomService", b =>
                {
                    b.HasOne("conference_rooms.Domain.Booking", null)
                        .WithMany("SelectedServices")
                        .HasForeignKey("BookingId");

                    b.HasOne("conference_rooms.Domain.Room", null)
                        .WithMany("Services")
                        .HasForeignKey("RoomId");
                });

            modelBuilder.Entity("conference_rooms.Domain.Booking", b =>
                {
                    b.Navigation("SelectedServices");
                });

            modelBuilder.Entity("conference_rooms.Domain.Room", b =>
                {
                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
